[tool.poetry]
name = "cpp-msgpack-rpc"
version = "0.0.0"
description = ""
authors = ["Kenta Kabashima <kenta_program37@hotmail.co.jp>"]
readme = "README.md"
packages = []
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
# Some tools implicitly require setuptools.
setuptools = "^75.6.0"

[tool.poetry.group.doc.dependencies]
myst-parser = "^4.0.0"
sphinx = "^8.1.3"
sphinx-autobuild = "^2024.10.3"
sphinxcontrib-plantuml = "^0.30"
sphinx-orange-book-theme = "^0.14.0"
breathe = "^4.35.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-approvaltests = "^0.2.4"
msgpack = "^1.1.0"
pytest-asyncio = "^0.25.0"
psutil = "^6.1.1"
pandas = "^2.2.3"
plotly = "^5.24.1"
kaleido = "==0.2.1"
statsmodels = "^0.14.4"
fastjsonschema = "^2.21.1"
pytomlpp = "^1.0.13"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
click = "^8.1.8"
cmakelang = "^0.6.13"
doc8 = "^1.1.2"
pre-commit = "^4.0.1"
clang-tidy-checker = "^0.5.0"
lcov_cobertura = "^2.0.2"
tqdm = "^4.67.1"
lizard = "^1.17.13"
isort = "^5.13.2"
jsonschema2md = "^1.3.0"
pylint = "^3.3.3"
flake8 = "^7.1.1"
mypy = "^1.14.0"
pandas-stubs = "^2.2.3.241126"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.main]
disable = "too-many-instance-attributes,line-too-long,fixme"
load-plugins = "pylint.extensions.docparams"

[tool.isort]
profile = "black"
