set(SOURCE_FILES
    addresses/address_test.cpp
    addresses/tcp_address_test.cpp
    catch_event_listener.cpp
    common/status_code_test.cpp
    common/status_test.cpp
    config/executor_config_test.cpp
    config/message_parser_config_test.cpp
    create_test_logger.cpp
    executors/general_executor_test.cpp
    executors/single_thread_executor_test.cpp
    logging/source_location_view_test.cpp
    messages/call_result_test.cpp
    messages/impl/parse_message_from_object_test.cpp
    messages/message_parser_test.cpp
    messages/message_serializer_test.cpp
    messages/message_type_test.cpp
    messages/method_name_test.cpp
    messages/method_name_view_test.cpp
    messages/parsed_parameters_test.cpp
    test_main.cpp
)
