set(SOURCE_FILES
    common/status_code_test.cpp
    common/status_test.cpp
    messages/call_result_test.cpp
    messages/impl/parse_message_from_object_test.cpp
    messages/message_parser_test.cpp
    messages/message_serializer_test.cpp
    messages/message_type_test.cpp
    messages/method_name_test.cpp
    messages/method_name_view_test.cpp
    messages/parsed_parameters_test.cpp
)
