#include "common/status_code_test.cpp"    // NOLINT(bugprone-suspicious-include)
#include "common/status_test.cpp"         // NOLINT(bugprone-suspicious-include)
#include "messages/call_result_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "messages/impl/parse_message_from_object_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "messages/message_parser_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "messages/message_serializer_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "messages/message_type_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "messages/parsed_parameters_test.cpp"  // NOLINT(bugprone-suspicious-include)
