#include "acceptor_test.cpp"         // NOLINT(bugprone-suspicious-include)
#include "catch_event_listener.cpp"  // NOLINT(bugprone-suspicious-include)
#include "create_test_logger.cpp"    // NOLINT(bugprone-suspicious-include)
#include "resolver_test.cpp"         // NOLINT(bugprone-suspicious-include)
#include "send_message_test.cpp"     // NOLINT(bugprone-suspicious-include)
