#include "call_methods_test.cpp"     // NOLINT(bugprone-suspicious-include)
#include "catch_event_listener.cpp"  // NOLINT(bugprone-suspicious-include)
#include "create_test_logger.cpp"    // NOLINT(bugprone-suspicious-include)
#include "many_calls_test.cpp"       // NOLINT(bugprone-suspicious-include)
#include "notifications_test.cpp"    // NOLINT(bugprone-suspicious-include)
#include "reconnection_test.cpp"     // NOLINT(bugprone-suspicious-include)
