set(SOURCE_FILES
    msgpack_rpc/common/status.cpp
    msgpack_rpc/common/status_code.cpp
    msgpack_rpc/config/message_parser_config.cpp
    msgpack_rpc/executors/single_thread_executor.cpp
    msgpack_rpc/logging/log_sinks.cpp
    msgpack_rpc/messages/message_parser.cpp
    msgpack_rpc/messages/message_type.cpp
)
